#================================
        #Application Name
#================================
spring:
  application:
    name: Mailer-App
#================================
        #Server Port Number
#================================
server:
  port: 8452
