#================================
        #Server Port Number
#================================
server:
  port: 8452
#================================
        #Application Name
#================================
spring:
  application:
    name: Mailer-App
#=================================
#Mailer Properties
#=================================
  mail:
    host: smtp.gmail.com
    port: 587
    username: vikas626639@gmail.com
    password: passwordkyah
    protocol: smtp
    tls: true
#    properties.mail.smtp:
#        auth: true
#        starttls.enable: true
#        ssl.trust: smtp.gmail.com
